import { BellRing } from 'lucide-react'
import Placeholder from './Placeholder'

export default function Alerts() {
  return (
    <Placeholder
      icon={BellRing}
      title="Alerts"
      description="Configurable threshold alerts and anomaly notifications generated by the Alert Agent will appear here."
    />
  )
}
